config/routes.rb
Mobiletest::Application.routes.draw do

  match 'details' => 'main#details'

   root :to => 'main#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def details
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html - Copy.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobiletest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : "<%= ENV['FACEBOOK_APP_ID'] %>",                        // App ID from the app dashboard
      //channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel file for x-domain comms
      status     : true,                                 // Check Facebook Login status
      xfbml      : true                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= render 'partials/header' %>


<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobiletest</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : "<%= ENV['FACEBOOK_APP_ID'] %>",                        // App ID from the app dashboard
      //channelUrl : '//WWW.YOUR_DOMAIN.COM/channel.html', // Channel file for x-domain comms
      status     : true,                                 // Check Facebook Login status
      xfbml      : true                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };

  // Load the SDK asynchronously
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/all.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= render 'partials/header' %>


<%= yield %>

</body>
</html>

app/views/main/details.html.erb
	<div data-role="content">
		details

	</div>

	<div data-role="footer">
	  <%= link_to 'Test', '#' , "data-icon" => "star"%>
	</div>

</div>

app/views/main/index.html - Copy.erb
<div class="fb-login-button" data-show-faces="false" data-width="200" data-max-rows="1"></div>

	<div data-role="content">
		<table>
			<tr><td>
				<div data-role="controlgroup" data-type="horizontal">
				    <a href="#" data-role="button">Walking</a>
				    <a href="#" data-role="button">Quick Taxi</a>
				    <a href="#" data-role="button">Subway</a>
				</div>
			</td><tr>

			<tr><td>
				<div data-role="controlgroup" data-type="horizontal">
				    <a href="#" data-role="button">Morning</a>
				    <a href="#" data-role="button">Noon</a>
				    <a href="#" data-role="button">Evening</a>
				    <a href="#" data-role="button">Night</a>
				</div>
			</td><tr>

		</table>

	</div>

	<div data-role="footer">
	  <%= link_to 'Test', '#' , "data-icon" => "star" %>
	</div>

</div>

app/views/main/index.html.erb
<script type="text/javascript">
function test(){

FB.api('/me', function(response) {
  alert(response.name +'\n' + response.gender +'\n' + response.age_range);
});

}

</script>
 <div class="fb-login-button" autologoutlink="true" data-show-faces="false" data-width="200" data-max-rows="1">Facebook Login</div> 

<button onclick="test()">Show my Facebook details</button>

	<div data-role="content">
		<table>
			<tr><td>
				<div data-role="controlgroup" data-type="horizontal">
				    <a href="#" data-role="button">Walking</a>
				    <a href="#" data-role="button">Quick Taxi</a>
				    <a href="#" data-role="button">Subway</a>
				</div>
			</td><tr>

			<tr><td>
				<div data-role="controlgroup" data-type="horizontal">
				    <a href="#" data-role="button">Morning</a>
				    <a href="#" data-role="button">Noon</a>
				    <a href="#" data-role="button">Evening</a>
				    <a href="#" data-role="button">Night</a>
				</div>
			</td><tr>

		</table>

	</div>

	<div data-role="footer">
	  <%= link_to 'Test', '#' , "data-icon" => "star" %>
	</div>

<!-- </div> -->

app/views/partials/_header.html.erb
<div data-role="page" data-add-back-btn="true">

  <div data-role="header">
    <a href="#" data-rel="back">back</a>
    <%= link_to 'Details', details_path %>
    <h1>Localizer</h1>
  </div>